// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef SPACE_ODB_ODB_HXX
#define SPACE_ODB_ODB_HXX

// Begin prologue.
//
#include <odb/boost/version.hxx>
#if ODB_BOOST_VERSION != 2050000 // 2.5.0
#  error ODB and C++ compilers see different libodb-boost interface versions
#endif
#include <odb/boost/date-time/pgsql/gregorian-traits.hxx>
#include <odb/boost/date-time/pgsql/posix-time-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "SpaceOdb.hpp"

#include "modules/users/adapters/persistence/UserOdb-odb.hxx"
#include "shared/adapters/persistence/odb/BaseOdb-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // SpaceOdb
  //
  template <>
  struct class_traits< ::SpaceOdb >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::SpaceOdb >
  {
    public:
    typedef ::SpaceOdb object_type;
    typedef ::SpaceOdb* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef object_traits< ::BaseOdb >::id_type id_type;

    static const bool auto_id = object_traits< ::BaseOdb >::auto_id;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // SpaceOdb
  //
  template <typename A>
  struct pointer_query_columns< ::SpaceOdb, id_pgsql, A >:
    pointer_query_columns< ::BaseOdb, id_pgsql, A >
  {
    // BaseOdb
    //
    typedef pointer_query_columns< ::BaseOdb, id_pgsql, A > BaseOdb;

    // title
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    title_type_;

    static const title_type_ title;

    // description
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::basic_string< char >,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    description_type_;

    static const description_type_ description;

    // owner
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    owner_type_;

    static const owner_type_ owner;
  };

  template <typename A>
  const typename pointer_query_columns< ::SpaceOdb, id_pgsql, A >::title_type_
  pointer_query_columns< ::SpaceOdb, id_pgsql, A >::
  title (A::table_name, "\"title\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::SpaceOdb, id_pgsql, A >::description_type_
  pointer_query_columns< ::SpaceOdb, id_pgsql, A >::
  description (A::table_name, "\"description\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::SpaceOdb, id_pgsql, A >::owner_type_
  pointer_query_columns< ::SpaceOdb, id_pgsql, A >::
  owner (A::table_name, "\"owner_id\"", 0);

  template <>
  class access::object_traits_impl< ::SpaceOdb, id_pgsql >:
    public access::object_traits< ::SpaceOdb >
  {
    public:
    typedef object_traits_impl< ::BaseOdb, id_pgsql >::id_image_type id_image_type;

    struct image_type: object_traits_impl< ::BaseOdb, id_pgsql >::image_type
    {
      // title_
      //
      details::buffer title_value;
      std::size_t title_size;
      bool title_null;

      // description_
      //
      details::buffer description_value;
      std::size_t description_size;
      bool description_null;

      // owner_
      //
      long long owner_value;
      bool owner_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    // members_
    //
    struct members_traits
    {
      static const char select_name[];
      static const char insert_name[];
      static const char delete_name[];

      static const unsigned int insert_types[];

      static const std::size_t id_column_count = 1UL;
      static const std::size_t data_column_count = 2UL;

      static const bool versioned = false;

      static const char insert_statement[];
      static const char select_statement[];
      static const char delete_statement[];

      typedef ::std::vector< ::odb::lazy_shared_ptr< ::UserOdb > > container_type;
      typedef
      odb::access::container_traits<container_type>
      container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef pgsql::container_statements< members_traits > statements_type;

      struct data_image_type
      {
        // value
        //
        long long value_value;
        bool value_null;

        std::size_t version;
      };

      static void
      bind (pgsql::bind*,
            const pgsql::bind* id,
            std::size_t id_size,
            data_image_type&);

      static void
      grow (data_image_type&,
            bool*);

      static void
      init (data_image_type&,
            const value_type&);

      static void
      init (value_type&,
            const data_image_type&,
            database*);

      static void
      insert (index_type, const value_type&, void*);

      static bool
      select (index_type&, value_type&, void*);

      static void
      delete_ (void*);

      static void
      persist (const container_type&,
               statements_type&);

      static void
      load (container_type&,
            statements_type&);

      static void
      update (const container_type&,
              statements_type&);

      static void
      erase (statements_type&);
    };

    struct owner_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 4UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    static const std::size_t batch = 1UL;

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::SpaceOdb, id_common >:
    public access::object_traits_impl< ::SpaceOdb, id_pgsql >
  {
  };

  // SpaceOdb
  //
  template <>
  struct alias_traits<
    ::UserOdb,
    id_pgsql,
    access::object_traits_impl< ::SpaceOdb, id_pgsql >::owner_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::SpaceOdb, id_pgsql >
  {
    // owner
    //
    typedef
    odb::alias_traits<
      ::UserOdb,
      id_pgsql,
      access::object_traits_impl< ::SpaceOdb, id_pgsql >::owner_tag>
    owner_alias_;
  };

  template <typename A>
  struct query_columns< ::SpaceOdb, id_pgsql, A >:
    query_columns_base< ::SpaceOdb, id_pgsql >,
    query_columns< ::BaseOdb, id_pgsql, A >
  {
    // BaseOdb
    //
    typedef query_columns< ::BaseOdb, id_pgsql, A > BaseOdb;

    // title
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    title_type_;

    static const title_type_ title;

    // description
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::basic_string< char >,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    description_type_;

    static const description_type_ description;

    // owner
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    owner_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::UserOdb,
        id_pgsql,
        owner_alias_ > >
    owner_pointer_type_;

    struct owner_type_: owner_pointer_type_, owner_column_type_
    {
      owner_type_ (const char* t, const char* c, const char* conv)
        : owner_column_type_ (t, c, conv)
      {
      }
    };

    static const owner_type_ owner;
  };

  template <typename A>
  const typename query_columns< ::SpaceOdb, id_pgsql, A >::title_type_
  query_columns< ::SpaceOdb, id_pgsql, A >::
  title (A::table_name, "\"title\"", 0);

  template <typename A>
  const typename query_columns< ::SpaceOdb, id_pgsql, A >::description_type_
  query_columns< ::SpaceOdb, id_pgsql, A >::
  description (A::table_name, "\"description\"", 0);

  template <typename A>
  const typename query_columns< ::SpaceOdb, id_pgsql, A >::owner_type_
  query_columns< ::SpaceOdb, id_pgsql, A >::
  owner (A::table_name, "\"owner_id\"", 0);
}

#include "SpaceOdb-odb.ixx"

#include <odb/post.hxx>

#endif // SPACE_ODB_ODB_HXX
