/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "space_members" CASCADE;

DROP TABLE IF EXISTS "spaces" CASCADE;

CREATE TABLE "spaces" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "title" VARCHAR(255) NOT NULL,
  "description" TEXT NULL,
  "owner_id" BIGINT NOT NULL);

CREATE TABLE "space_members" (
  "space_id" BIGINT NOT NULL,
  "user_id" BIGINT NOT NULL,
  CONSTRAINT "space_id_fk"
    FOREIGN KEY ("space_id")
    REFERENCES "spaces" ("id")
    ON DELETE CASCADE);

CREATE INDEX "space_members_space_id_i"
  ON "space_members" ("space_id");

ALTER TABLE "spaces"
  ADD CONSTRAINT "owner_id_fk"
    FOREIGN KEY ("owner_id")
    REFERENCES "users" ("id")
    INITIALLY DEFERRED;

ALTER TABLE "space_members"
  ADD CONSTRAINT "user_id_fk"
    FOREIGN KEY ("user_id")
    REFERENCES "users" ("id")
    INITIALLY DEFERRED;

