/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "automations" CASCADE;

CREATE TABLE "automations" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "config" TEXT NOT NULL);

