/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "task_labels" CASCADE;

DROP TABLE IF EXISTS "tasks" CASCADE;

CREATE TABLE "tasks" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "title" VARCHAR(255) NOT NULL,
  "description" TEXT NOT NULL,
  "create_date" TIMESTAMP NULL,
  "update_date" TIMESTAMP NULL,
  "due_date" TIMESTAMP NULL,
  "assignee_id" BIGINT NULL,
  "reporter_id" BIGINT NULL,
  "priority" INT NOT NULL,
  "type" VARCHAR(255) NULL);

CREATE TABLE "task_labels" (
  "task_id" BIGINT NOT NULL,
  "label" TEXT NOT NULL,
  CONSTRAINT "task_id_fk"
    FOREIGN KEY ("task_id")
    REFERENCES "tasks" ("id")
    ON DELETE CASCADE);

CREATE INDEX "task_labels_task_id_i"
  ON "task_labels" ("task_id");

ALTER TABLE "tasks"
  ADD CONSTRAINT "assignee_id_fk"
    FOREIGN KEY ("assignee_id")
    REFERENCES "public"."users" ("id")
    INITIALLY DEFERRED,
  ADD CONSTRAINT "reporter_id_fk"
    FOREIGN KEY ("reporter_id")
    REFERENCES "public"."users" ("id")
    INITIALLY DEFERRED;

