// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "TaskOdb-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // TaskOdb
  //

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::
  persist_statement_name[] = "persist_TaskOdb";

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::
  find_statement_name[] = "find_TaskOdb";

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::
  update_statement_name[] = "update_TaskOdb";

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::
  erase_statement_name[] = "erase_TaskOdb";

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::
  query_statement_name[] = "query_TaskOdb";

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::
  erase_query_statement_name[] = "erase_query_TaskOdb";

  const unsigned int access::object_traits_impl< ::TaskOdb, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::int8_oid,
    pgsql::int8_oid,
    pgsql::int4_oid,
    pgsql::text_oid
  };

  const unsigned int access::object_traits_impl< ::TaskOdb, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::TaskOdb, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::int8_oid,
    pgsql::int8_oid,
    pgsql::int4_oid,
    pgsql::text_oid,
    pgsql::int8_oid
  };

  const char alias_traits<  ::UserOdb,
    id_pgsql,
    access::object_traits_impl< ::TaskOdb, id_pgsql >::assignee_tag>::
  table_name[] = "\"assignee_id\"";

  const char alias_traits<  ::UserOdb,
    id_pgsql,
    access::object_traits_impl< ::TaskOdb, id_pgsql >::reporter_tag>::
  table_name[] = "\"reporter_id\"";

  struct access::object_traits_impl< ::TaskOdb, id_pgsql >::extra_statement_cache_type
  {
    pgsql::container_statements_impl< labels_traits > labels_;

    extra_statement_cache_type (
      pgsql::connection& c,
      image_type&,
      id_image_type&,
      pgsql::binding& id,
      pgsql::binding&,
      pgsql::native_binding& idn,
      const unsigned int* idt)
    : labels_ (c, id, idn, idt)
    {
    }
  };

  // labels_
  //

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  select_name[] = "select_TaskOdb_labels";

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  insert_name[] = "insert_TaskOdb_labels";

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  delete_name[] = "delete_TaskOdb_labels";

  const unsigned int access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  insert_types[] =
  {
    pgsql::int8_oid,
    pgsql::text_oid
  };

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  select_statement[] =
  "SELECT "
  "\"task_labels\".\"label\" "
  "FROM \"task_labels\" "
  "WHERE \"task_labels\".\"task_id\"=$1";

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  insert_statement[] =
  "INSERT INTO \"task_labels\" "
  "(\"task_id\", "
  "\"label\") "
  "VALUES "
  "($1, $2)";

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  delete_statement[] =
  "DELETE FROM \"task_labels\" "
  "WHERE \"task_id\"=$1";

  void access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  bind (pgsql::bind* b,
        const pgsql::bind* id,
        std::size_t id_size,
        data_image_type& d)
  {
    using namespace pgsql;

    statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    size_t n (0);

    // object_id
    //
    if (id != 0)
      std::memcpy (&b[n], id, id_size * sizeof (id[0]));
    n += id_size;

    // value
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = d.value_value.data_ptr ();
    b[n].capacity = d.value_value.capacity ();
    b[n].size = &d.value_size;
    b[n].is_null = &d.value_null;
  }

  void access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  grow (data_image_type& i,
        bool* t)
  {
    bool grew (false);

    // value
    //
    if (t[0UL])
    {
      i.value_value.capacity (i.value_size);
      grew = true;
    }

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  init (data_image_type& i,
        const value_type& v)
  {
    using namespace pgsql;

    statement_kind sk (statement_insert);
    ODB_POTENTIALLY_UNUSED (sk);

    bool grew (false);

    // value
    //
    {
      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.value_value.capacity ());
      pgsql::value_traits<
          value_type,
          pgsql::id_string >::set_image (
        i.value_value,
        size,
        is_null,
        v);
      i.value_null = is_null;
      i.value_size = size;
      grew = grew || (cap != i.value_value.capacity ());
    }

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  init (value_type& v,
        const data_image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    // value
    //
    {
      pgsql::value_traits<
          value_type,
          pgsql::id_string >::set_value (
        v,
        i.value_value,
        i.value_size,
        i.value_null);
    }
  }

  void access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  insert (const value_type& v, void* d)
  {
    using namespace pgsql;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (di, v);

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    if (!sts.insert_statement ().execute ())
      throw object_already_persistent ();
  }

  bool access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  select (value_type& v, void* d)
  {
    using namespace pgsql;
    using pgsql::select_statement;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (v, di, &sts.connection ().database ());

    select_statement& st (sts.select_statement ());
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      grow (di, sts.select_image_truncated ());

      if (sts.data_binding_test_version ())
      {
        bind (sts.data_bind (), 0, sts.id_binding ().count, di);
        sts.data_binding_update_version ();
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  delete_ (void* d)
  {
    using namespace pgsql;

    statements_type& sts (*static_cast< statements_type* > (d));
    sts.delete_statement ().execute ();
  }

  void access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  persist (const container_type& c,
           statements_type& sts)
  {
    using namespace pgsql;

    functions_type& fs (sts.functions ());
    container_traits_type::persist (c, fs);
  }

  void access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  load (container_type& c,
        statements_type& sts)
  {
    using namespace pgsql;
    using pgsql::select_statement;

    const binding& id (sts.id_binding ());

    if (sts.data_binding_test_version ())
    {
      bind (sts.data_bind (), id.bind, id.count, sts.data_image ());
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      data_image_type& di (sts.data_image ());
      grow (di, sts.select_image_truncated ());

      if (sts.data_binding_test_version ())
      {
        bind (sts.data_bind (), 0, id.count, di);
        sts.data_binding_update_version ();
        st.refetch ();
      }
    }

    bool more (r != select_statement::no_data);

    functions_type& fs (sts.functions ());
    container_traits_type::load (c, more, fs);
  }

  void access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  update (const container_type& c,
          statements_type& sts)
  {
    using namespace pgsql;

    functions_type& fs (sts.functions ());
    container_traits_type::update (c, fs);
  }

  void access::object_traits_impl< ::TaskOdb, id_pgsql >::labels_traits::
  erase (statements_type& sts)
  {
    using namespace pgsql;

    functions_type& fs (sts.functions ());
    container_traits_type::erase (fs);
  }

  bool access::object_traits_impl< ::TaskOdb, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // BaseOdb base
    //
    if (object_traits_impl< ::BaseOdb, id_pgsql >::grow (
          i, t + 0UL))
      grew = true;

    // title_
    //
    if (t[1UL])
    {
      i.title_value.capacity (i.title_size);
      grew = true;
    }

    // description_
    //
    if (t[2UL])
    {
      i.description_value.capacity (i.description_size);
      grew = true;
    }

    // create_date_
    //
    t[3UL] = 0;

    // update_date_
    //
    t[4UL] = 0;

    // due_date_
    //
    t[5UL] = 0;

    // assignee_
    //
    t[6UL] = 0;

    // reporter_
    //
    t[7UL] = 0;

    // priority_
    //
    t[8UL] = 0;

    // type_
    //
    if (t[9UL])
    {
      i.type_value.capacity (i.type_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::TaskOdb, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // BaseOdb base
    //
    object_traits_impl< ::BaseOdb, id_pgsql >::bind (b + n, i, sk);
    n += sk == statement_select ? 1UL : 0UL;

    // title_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.title_value.data_ptr ();
    b[n].capacity = i.title_value.capacity ();
    b[n].size = &i.title_size;
    b[n].is_null = &i.title_null;
    n++;

    // description_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.description_value.data_ptr ();
    b[n].capacity = i.description_value.capacity ();
    b[n].size = &i.description_size;
    b[n].is_null = &i.description_null;
    n++;

    // create_date_
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.create_date_value;
    b[n].is_null = &i.create_date_null;
    n++;

    // update_date_
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.update_date_value;
    b[n].is_null = &i.update_date_null;
    n++;

    // due_date_
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.due_date_value;
    b[n].is_null = &i.due_date_null;
    n++;

    // assignee_
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.assignee_value;
    b[n].is_null = &i.assignee_null;
    n++;

    // reporter_
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.reporter_value;
    b[n].is_null = &i.reporter_null;
    n++;

    // priority_
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.priority_value;
    b[n].is_null = &i.priority_null;
    n++;

    // type_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.type_value.data_ptr ();
    b[n].capacity = i.type_value.capacity ();
    b[n].size = &i.type_size;
    b[n].is_null = &i.type_null;
    n++;
  }

  bool access::object_traits_impl< ::TaskOdb, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // BaseOdb base
    //
    if (object_traits_impl< ::BaseOdb, id_pgsql >::init (i, o, sk))
      grew = true;

    // title_
    //
    {
      ::std::string const& v =
        o.title_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.title_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.title_value,
        size,
        is_null,
        v);
      i.title_null = is_null;
      i.title_size = size;
      grew = grew || (cap != i.title_value.capacity ());
    }

    // description_
    //
    {
      ::std::string const& v =
        o.description_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.description_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.description_value,
        size,
        is_null,
        v);
      i.description_null = is_null;
      i.description_size = size;
      grew = grew || (cap != i.description_value.capacity ());
    }

    // create_date_
    //
    {
      ::boost::posix_time::ptime const& v =
        o.create_date_;

      bool is_null (true);
      pgsql::value_traits<
          ::boost::posix_time::ptime,
          pgsql::id_timestamp >::set_image (
        i.create_date_value, is_null, v);
      i.create_date_null = is_null;
    }

    // update_date_
    //
    {
      ::boost::posix_time::ptime const& v =
        o.update_date_;

      bool is_null (true);
      pgsql::value_traits<
          ::boost::posix_time::ptime,
          pgsql::id_timestamp >::set_image (
        i.update_date_value, is_null, v);
      i.update_date_null = is_null;
    }

    // due_date_
    //
    {
      ::odb::nullable< ::boost::posix_time::ptime > const& v =
        o.due_date_;

      bool is_null (true);
      pgsql::value_traits<
          ::odb::nullable< ::boost::posix_time::ptime >,
          pgsql::id_timestamp >::set_image (
        i.due_date_value, is_null, v);
      i.due_date_null = is_null;
    }

    // assignee_
    //
    {
      ::odb::lazy_shared_ptr< ::UserOdb > const& v =
        o.assignee_;

      typedef object_traits< ::UserOdb > obj_traits;
      typedef odb::pointer_traits< ::odb::lazy_shared_ptr< ::UserOdb > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& ptr_id (
          ptr_traits::object_id< ptr_traits::element_type  > (v));

        pgsql::value_traits<
            obj_traits::id_type,
            pgsql::id_bigint >::set_image (
          i.assignee_value, is_null, ptr_id);
        i.assignee_null = is_null;
      }
      else
        i.assignee_null = true;
    }

    // reporter_
    //
    {
      ::odb::lazy_shared_ptr< ::UserOdb > const& v =
        o.reporter_;

      typedef object_traits< ::UserOdb > obj_traits;
      typedef odb::pointer_traits< ::odb::lazy_shared_ptr< ::UserOdb > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& ptr_id (
          ptr_traits::object_id< ptr_traits::element_type  > (v));

        pgsql::value_traits<
            obj_traits::id_type,
            pgsql::id_bigint >::set_image (
          i.reporter_value, is_null, ptr_id);
        i.reporter_null = is_null;
      }
      else
        i.reporter_null = true;
    }

    // priority_
    //
    {
      ::TaskPriority const& v =
        o.priority_;

      bool is_null (false);
      pgsql::value_traits<
          ::TaskPriority,
          pgsql::id_integer >::set_image (
        i.priority_value, is_null, v);
      i.priority_null = is_null;
    }

    // type_
    //
    {
      ::odb::nullable< ::std::basic_string< char > > const& v =
        o.type_;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.type_value.capacity ());
      pgsql::value_traits<
          ::odb::nullable< ::std::basic_string< char > >,
          pgsql::id_string >::set_image (
        i.type_value,
        size,
        is_null,
        v);
      i.type_null = is_null;
      i.type_size = size;
      grew = grew || (cap != i.type_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::TaskOdb, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // BaseOdb base
    //
    object_traits_impl< ::BaseOdb, id_pgsql >::init (o, i, db);

    // title_
    //
    {
      ::std::string& v =
        o.title_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.title_value,
        i.title_size,
        i.title_null);
    }

    // description_
    //
    {
      ::std::string& v =
        o.description_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.description_value,
        i.description_size,
        i.description_null);
    }

    // create_date_
    //
    {
      ::boost::posix_time::ptime& v =
        o.create_date_;

      pgsql::value_traits<
          ::boost::posix_time::ptime,
          pgsql::id_timestamp >::set_value (
        v,
        i.create_date_value,
        i.create_date_null);
    }

    // update_date_
    //
    {
      ::boost::posix_time::ptime& v =
        o.update_date_;

      pgsql::value_traits<
          ::boost::posix_time::ptime,
          pgsql::id_timestamp >::set_value (
        v,
        i.update_date_value,
        i.update_date_null);
    }

    // due_date_
    //
    {
      ::odb::nullable< ::boost::posix_time::ptime >& v =
        o.due_date_;

      pgsql::value_traits<
          ::odb::nullable< ::boost::posix_time::ptime >,
          pgsql::id_timestamp >::set_value (
        v,
        i.due_date_value,
        i.due_date_null);
    }

    // assignee_
    //
    {
      ::odb::lazy_shared_ptr< ::UserOdb >& v =
        o.assignee_;

      typedef object_traits< ::UserOdb > obj_traits;
      typedef odb::pointer_traits< ::odb::lazy_shared_ptr< ::UserOdb > > ptr_traits;

      if (i.assignee_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type ptr_id;
        pgsql::value_traits<
            obj_traits::id_type,
            pgsql::id_bigint >::set_value (
          ptr_id,
          i.assignee_value,
          i.assignee_null);

        v = ptr_traits::pointer_type (
          *static_cast<pgsql::database*> (db), ptr_id);
      }
    }

    // reporter_
    //
    {
      ::odb::lazy_shared_ptr< ::UserOdb >& v =
        o.reporter_;

      typedef object_traits< ::UserOdb > obj_traits;
      typedef odb::pointer_traits< ::odb::lazy_shared_ptr< ::UserOdb > > ptr_traits;

      if (i.reporter_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type ptr_id;
        pgsql::value_traits<
            obj_traits::id_type,
            pgsql::id_bigint >::set_value (
          ptr_id,
          i.reporter_value,
          i.reporter_null);

        v = ptr_traits::pointer_type (
          *static_cast<pgsql::database*> (db), ptr_id);
      }
    }

    // priority_
    //
    {
      ::TaskPriority& v =
        o.priority_;

      pgsql::value_traits<
          ::TaskPriority,
          pgsql::id_integer >::set_value (
        v,
        i.priority_value,
        i.priority_null);
    }

    // type_
    //
    {
      ::odb::nullable< ::std::basic_string< char > >& v =
        o.type_;

      pgsql::value_traits<
          ::odb::nullable< ::std::basic_string< char > >,
          pgsql::id_string >::set_value (
        v,
        i.type_value,
        i.type_size,
        i.type_null);
    }
  }

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::persist_statement[] =
  "INSERT INTO \"tasks\" "
  "(\"id\", "
  "\"title\", "
  "\"description\", "
  "\"create_date\", "
  "\"update_date\", "
  "\"due_date\", "
  "\"assignee_id\", "
  "\"reporter_id\", "
  "\"priority\", "
  "\"type\") "
  "VALUES "
  "(DEFAULT, $1, $2, $3, $4, $5, $6, $7, $8, $9) "
  "RETURNING \"id\"";

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::find_statement[] =
  "SELECT "
  "\"tasks\".\"id\", "
  "\"tasks\".\"title\", "
  "\"tasks\".\"description\", "
  "\"tasks\".\"create_date\", "
  "\"tasks\".\"update_date\", "
  "\"tasks\".\"due_date\", "
  "\"tasks\".\"assignee_id\", "
  "\"tasks\".\"reporter_id\", "
  "\"tasks\".\"priority\", "
  "\"tasks\".\"type\" "
  "FROM \"tasks\" "
  "WHERE \"tasks\".\"id\"=$1";

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::update_statement[] =
  "UPDATE \"tasks\" "
  "SET "
  "\"title\"=$1, "
  "\"description\"=$2, "
  "\"create_date\"=$3, "
  "\"update_date\"=$4, "
  "\"due_date\"=$5, "
  "\"assignee_id\"=$6, "
  "\"reporter_id\"=$7, "
  "\"priority\"=$8, "
  "\"type\"=$9 "
  "WHERE \"id\"=$10";

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::erase_statement[] =
  "DELETE FROM \"tasks\" "
  "WHERE \"id\"=$1";

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::query_statement[] =
  "SELECT\n"
  "\"tasks\".\"id\",\n"
  "\"tasks\".\"title\",\n"
  "\"tasks\".\"description\",\n"
  "\"tasks\".\"create_date\",\n"
  "\"tasks\".\"update_date\",\n"
  "\"tasks\".\"due_date\",\n"
  "\"tasks\".\"assignee_id\",\n"
  "\"tasks\".\"reporter_id\",\n"
  "\"tasks\".\"priority\",\n"
  "\"tasks\".\"type\"\n"
  "FROM \"tasks\"\n"
  "LEFT JOIN \"public\".\"users\" AS \"assignee_id\" ON \"assignee_id\".\"id\"=\"tasks\".\"assignee_id\"\n"
  "LEFT JOIN \"public\".\"users\" AS \"reporter_id\" ON \"reporter_id\".\"id\"=\"tasks\".\"reporter_id\"";

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"tasks\"";

  const char access::object_traits_impl< ::TaskOdb, id_pgsql >::table_name[] =
  "\"tasks\"";

  void access::object_traits_impl< ::TaskOdb, id_pgsql >::
  persist (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id_ = id (sts.id_image ());

    id_image_type& i (sts.id_image ());
    init (i, id (obj));

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // labels_
    //
    {
      ::std::unordered_set< ::std::basic_string< char > > const& v =
        obj.labels_;

      labels_traits::persist (
        v,
        esc.labels_);
    }

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::TaskOdb, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // labels_
    //
    {
      ::std::unordered_set< ::std::basic_string< char > > const& v =
        obj.labels_;

      labels_traits::update (
        v,
        esc.labels_);
    }

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::TaskOdb, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // labels_
    //
    {
      labels_traits::erase (
        esc.labels_);
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::TaskOdb, id_pgsql >::pointer_type
  access::object_traits_impl< ::TaskOdb, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::TaskOdb, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::TaskOdb, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::TaskOdb, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::TaskOdb, id_pgsql >::
  load_ (statements_type& sts,
         object_type& obj,
         bool reload)
  {
    ODB_POTENTIALLY_UNUSED (reload);

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // labels_
    //
    {
      ::std::unordered_set< ::std::basic_string< char > >& v =
        obj.labels_;

      labels_traits::load (
        v,
        esc.labels_);
    }
  }

  result< access::object_traits_impl< ::TaskOdb, id_pgsql >::object_type >
  access::object_traits_impl< ::TaskOdb, id_pgsql >::
  query (database& db, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        true,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::TaskOdb, id_pgsql >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
