/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "board_category_tasks" CASCADE;

DROP TABLE IF EXISTS "board_categories" CASCADE;

CREATE TABLE "board_categories" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "title" VARCHAR(255) NOT NULL);

CREATE TABLE "board_category_tasks" (
  "board_category_id" BIGINT NOT NULL,
  "task_id" BIGINT NOT NULL,
  CONSTRAINT "board_category_id_fk"
    FOREIGN KEY ("board_category_id")
    REFERENCES "board_categories" ("id")
    ON DELETE CASCADE);

CREATE INDEX "board_category_tasks_board_category_id_i"
  ON "board_category_tasks" ("board_category_id");

ALTER TABLE "board_category_tasks"
  ADD CONSTRAINT "task_id_fk"
    FOREIGN KEY ("task_id")
    REFERENCES "tasks" ("id")
    INITIALLY DEFERRED;

