/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "board_category_boards" CASCADE;

DROP TABLE IF EXISTS "boards" CASCADE;

CREATE TABLE "boards" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "title" VARCHAR(255) NOT NULL,
  "description" TEXT NOT NULL);

CREATE TABLE "board_category_boards" (
  "board_id" BIGINT NOT NULL,
  "board_category_id" BIGINT NOT NULL,
  CONSTRAINT "board_id_fk"
    FOREIGN KEY ("board_id")
    REFERENCES "boards" ("id")
    ON DELETE CASCADE);

CREATE INDEX "board_category_boards_board_id_i"
  ON "board_category_boards" ("board_id");

ALTER TABLE "board_category_boards"
  ADD CONSTRAINT "board_category_id_fk"
    FOREIGN KEY ("board_category_id")
    REFERENCES "board_categories" ("id")
    INITIALLY DEFERRED;

