/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "group_members" CASCADE;

DROP TABLE IF EXISTS "groups" CASCADE;

CREATE TABLE "groups" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "permissions" TEXT NOT NULL);

CREATE TABLE "group_members" (
  "group_id" BIGINT NOT NULL,
  "user_id" BIGINT NOT NULL,
  CONSTRAINT "group_id_fk"
    FOREIGN KEY ("group_id")
    REFERENCES "groups" ("id")
    ON DELETE CASCADE);

CREATE INDEX "group_members_group_id_i"
  ON "group_members" ("group_id");

ALTER TABLE "group_members"
  ADD CONSTRAINT "user_id_fk"
    FOREIGN KEY ("user_id")
    REFERENCES "public"."users" ("id")
    INITIALLY DEFERRED;

