#pragma once

#include <odb/core.hxx>

#pragma db object abstract
/**
 * @brief Common ODB base for persistent entities with autogenerated id.
 *
 * Derived ODB models inherit identifier storage and can expose id via
 * lightweight accessors without duplicating mapping declarations.
 */
class BaseOdb
{
protected:
    friend class odb::access;

#pragma db id auto
    unsigned long id_ = 0;

public:
    BaseOdb() = default;
    explicit BaseOdb(unsigned long id) : id_(id) {}
    unsigned long id_value() const { return id_; }
};