// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

namespace odb
{
  // BaseOdb
  //

  inline
  access::object_traits< ::BaseOdb >::id_type
  access::object_traits< ::BaseOdb >::
  id (const object_type& o)
  {
    return o.id_;
  }
}

namespace odb
{
  // BaseOdb
  //
}

